title: "Hiroki Kuji"
description: "Quantum computing / many-body physics / QEC"
url: "https://hlrokl.github.io"   # ←ユーザーサイトなので空でないURL
baseurl: ""                        # ←ユーザーサイトは空文字
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
